[package]
name = "hd_practice_patcher"
version = "0.1.0"
edition = "2021"

[dependencies]
prompted = "0.2.8"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
